# typed: false
# frozen_string_literal: true

# Homebrew formula for Numan (Nushell package manager).
#
# Tap install:
#   brew tap tonythethompson/numan
#   brew install numan
#
# Generated by scripts/render_homebrew_formula.py — do not hand-edit digests.
# The Publish to Homebrew workflow updates this file and the homebrew-numan tap
# after each v*.*.* GitHub Release.

class Numan < Formula
  desc "Cross-platform package manager for Nushell"
  homepage "https://github.com/tonythethompson/numan"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tonythethompson/numan/releases/download/v#{version}/numan-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "02c213f9d08f592075273e6af1b03818c90dd5d38a3901893b5e296b8deb8bd0"
    end
    on_intel do
      odie "Numan no longer ships Intel Mac (x86_64) binaries. Use Apple Silicon, or `cargo install numan-cli`."
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tonythethompson/numan/releases/download/v#{version}/numan-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b6f42bc38e6ddeb9cad055a9596bbf1cda5caaff6ec794e9224b3e63f5f5bd51"
    end
  end

  def install
    arch_dir = Dir["numan-*"].first
    odie "expected numan-* directory in archive" if arch_dir.nil?

    bin.install "#{arch_dir}/numan"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/numan --version")
  end
end
