# typed: false
# frozen_string_literal: true

# Homebrew formula for Numan (Nushell package manager).
#
# Tap install (HTTPS remote avoids SSH host-key update failures):
#   brew tap tonythethompson/numan https://github.com/tonythethompson/homebrew-numan
#   brew install numan
#
# Generated by scripts/render_homebrew_formula.py — do not hand-edit digests.
# The Publish to Homebrew workflow updates this file and the homebrew-numan tap
# after each v*.*.* GitHub Release.

class Numan < Formula
  desc "Cross-platform package manager for Nushell"
  homepage "https://github.com/tonythethompson/numan"
  version "0.2.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tonythethompson/numan/releases/download/v#{version}/numan-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "6cc17178c1c151c044e3cb8b50fb57ec798bff35bf397a7686928e6437b24ccb"
    end
    on_intel do
      odie "Numan no longer ships Intel Mac (x86_64) binaries. Use Apple Silicon, or `cargo install numan-cli`."
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tonythethompson/numan/releases/download/v#{version}/numan-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "471793f00cfc8697ad0cdd1d0030af6768b77764b770efde193180a54bef839a"
    end
    on_arm do
      url "https://github.com/tonythethompson/numan/releases/download/v#{version}/numan-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "6fceccb9d6bc6db559ce7d409b595918ece7efe9eb03eb2727d13059529dd32e"
    end
  end

  def install
    # Homebrew stages into the archive's sole top-level directory, so the
    # binary is ./numan (not ./numan-*/numan).
    bin.install "numan"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/numan --version")
  end
end
