#!/usr/bin/env python3
"""Render packaging/homebrew/numan.rb from a release version + SHA256SUMS.

Usage:
  python scripts/render_homebrew_formula.py --version 0.1.5 --sha256sums SHA256SUMS
  python scripts/render_homebrew_formula.py --version 0.1.5 --sha256sums SHA256SUMS --write
  python scripts/render_homebrew_formula.py --check-url-layout   # verify known asset names
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO_ROOT / "packaging" / "homebrew" / "numan.rb"

# Release asset basename suffix -> Homebrew bottle platform key used in formula.
REQUIRED_ASSETS = {
    "aarch64-apple-darwin": "macos_arm",
    "x86_64-apple-darwin": "macos_intel",
    "x86_64-unknown-linux-gnu": "linux_intel",
}

ASSET_RE = re.compile(
    r"^([0-9a-f]{64})\s+numan-(?P<ver>[^-]+(?:\.[^-]+)*)-(?P<triple>[^\s]+)\.(?P<ext>tar\.gz|zip)$"
)


def parse_sha256sums(text: str, version: str) -> dict[str, str]:
    """Map triple -> lowercase sha256 for this version's archives."""
    found: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        match = ASSET_RE.match(line)
        if not match:
            continue
        if match.group("ver") != version:
            continue
        if match.group("ext") != "tar.gz":
            continue
        found[match.group("triple")] = match.group(1).lower()
    missing = [t for t in REQUIRED_ASSETS if t not in found]
    if missing:
        raise SystemExit(
            f"SHA256SUMS missing required .tar.gz assets for v{version}: {', '.join(missing)}"
        )
    return found


def render_formula(version: str, digests: dict[str, str]) -> str:
    mac_arm = digests["aarch64-apple-darwin"]
    mac_intel = digests["x86_64-apple-darwin"]
    linux_intel = digests["x86_64-unknown-linux-gnu"]
    return f"""# typed: false
# frozen_string_literal: true

# Homebrew formula for Numan (Nushell package manager).
#
# Tap install:
#   brew tap tonythethompson/numan
#   brew install numan
#
# Generated by scripts/render_homebrew_formula.py — do not hand-edit digests.
# The Publish to Homebrew workflow updates this file and the homebrew-numan tap
# after each v*.*.* GitHub Release.

class Numan < Formula
  desc "Cross-platform package manager for Nushell"
  homepage "https://github.com/tonythethompson/numan"
  version "{version}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/tonythethompson/numan/releases/download/v#{{version}}/numan-#{{version}}-aarch64-apple-darwin.tar.gz"
      sha256 "{mac_arm}"
    end
    on_intel do
      url "https://github.com/tonythethompson/numan/releases/download/v#{{version}}/numan-#{{version}}-x86_64-apple-darwin.tar.gz"
      sha256 "{mac_intel}"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tonythethompson/numan/releases/download/v#{{version}}/numan-#{{version}}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "{linux_intel}"
    end
  end

  def install
    arch_dir = Dir["numan-*"].first
    odie "expected numan-* directory in archive" if arch_dir.nil?

    bin.install "#{{arch_dir}}/numan"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/numan --version")
  end
end
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", help="Release version without v prefix (e.g. 0.1.5)")
    parser.add_argument(
        "--sha256sums",
        type=Path,
        help="Path to SHA256SUMS from the GitHub Release",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help=f"Write {DEFAULT_OUT}",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help="Output formula path",
    )
    parser.add_argument(
        "--check-url-layout",
        action="store_true",
        help="Print required asset names and exit",
    )
    args = parser.parse_args()

    if args.check_url_layout:
        print("Required release assets for Homebrew:")
        for triple in REQUIRED_ASSETS:
            print(f"  numan-<version>-{triple}.tar.gz")
        return 0

    if not args.version or not args.sha256sums:
        parser.error("--version and --sha256sums are required unless --check-url-layout")

    digests = parse_sha256sums(args.sha256sums.read_text(encoding="utf-8"), args.version)
    text = render_formula(args.version, digests)
    if args.write:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text, encoding="utf-8", newline="\n")
        print(f"Wrote {args.out}")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
